spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: payment
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  timezone: Asia/Seoul
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        partitioner.class: com.system.payment.payment.partitioner.ConsistentHashPartitioner
        enable.idempotence: true
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: local-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 역직렬화 안전장치: ErrorHandlingDeserializer로 감싸기
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # ErrorHandlingDeserializer가 실제로 사용할 delegate 지정
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.system.payment.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.system.payment.payment.model.dto.PaymentRequestedMessageV1"
      heartbeat-interval-ms: 3000
      session-timeout-ms: 30000
      max-poll-interval-ms: 600000
      max-poll-records: 1
      isolation-level: read_committed
    jmx:
      enabled: false
logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET}

sql:
  init-sign-up-secret-sql: ${INIT_SIGN_UP_SECRET_SQL}
  init-card-register-secret-sql: ${INIT_CARD_REGISTER_SECRET_SQL}

payment:
  request:
    topic: payment.requested.v1
  inicis:
    mid: INIBillTst
    api-key: q9G7rX1pT5vL2cN8