spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: payment
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      schema-locations: classpath:db/ddl.sql,classpath:db/init.sql
  timezone: Asia/Seoul

logging:
  level:
    root: INFO
