spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: payment
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  timezone: Asia/Seoul
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        partitioner.class: com.example.kafka.ConsistentHashPartitioner
        enable.idempotence: true
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: local-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      heartbeat-interval-ms: 3000
      session-timeout-ms: 30000
      max-poll-interval-ms: 300000
      properties:
        spring.json.trusted.packages: '*'
    jmx:
      enabled: false
logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET}