name: CI-CD (GKE with Artifact Registry)

on:
  workflow_dispatch:
#  push:
#    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  LOCATION: ${{ secrets.GKE_LOCATION }}       # REGION 대체
  REPO_NAME: payment-repo                     # AR 리포지토리명
  IMAGE_NAME: payment-api
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_URI: ${{ secrets.GKE_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/payment-repo/payment-api:${{ github.sha }}

jobs:
  build:
    environment: payment-system-env
    name: Build & Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-daemon

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_URI }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_URI }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    environment: payment-system-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 1. 최초에는 항상 apply! (없으면 생성, 있으면 변경)
      - name: Create/Update Deployment (최초 자동 service)
        run: kubectl apply -f k8s/service.yml

      - name: Create/Update Deployment (최초 자동 deployment)
        run: kubectl apply -f k8s/deployment.yml

      # 2. set image로 최신 이미지 롤링 업데이트 (있을 때만 동작)
      - name: Rolling update image
        run: kubectl set image deployment/payment-api payment-api=${{ env.IMAGE_URI }} --record

      - name: Wait for rollout to finish
        run: kubectl rollout status deployment/payment-api --timeout=120s

