name: CI-CD (GKE)

on:
  workflow_dispatch:
#  push:
#    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: payment-api
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_URI: gcr.io/${{ secrets.GCP_PROJECT_ID }}/payment-api:${{ github.sha }}

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-daemon

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry / GCR
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_URI }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_URI }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Update Kubernetes Deployment image
        run: kubectl set image deployment/payment-api payment-api=${{ env.IMAGE_URI }} --record

      - name: Wait for rollout to finish
        run: kubectl rollout status deployment/payment-api
